### ISSUE TITLE
dev-lang/ispc-1.12.0 fails to compile

### ISSUE THREAD

**Issue by gerion0** [redchillipadi/ebuild-overlay#10]
I got this error:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
clangASTPath
    linked by target "ispc" in directory /var/tmp/portage/dev-lang/ispc-1.12.0/work/ispc-1.12.0
clangAnalysisPath
    linked by target "ispc" in directory /var/tmp/portage/dev-lang/ispc-1.12.0/work/ispc-1.12.0
clangBasicPath
    linked by target "ispc" in directory /var/tmp/portage/dev-lang/ispc-1.12.0/work/ispc-1.12.0
clangDriverPath
    linked by target "ispc" in directory /var/tmp/portage/dev-lang/ispc-1.12.0/work/ispc-1.12.0
clangEditPath
    linked by target "ispc" in directory /var/tmp/portage/dev-lang/ispc-1.12.0/work/ispc-1.12.0
clangFrontendPath
    linked by target "ispc" in directory /var/tmp/portage/dev-lang/ispc-1.12.0/work/ispc-1.12.0
clangLexPath
    linked by target "ispc" in directory /var/tmp/portage/dev-lang/ispc-1.12.0/work/ispc-1.12.0
clangParsePath
    linked by target "ispc" in directory /var/tmp/portage/dev-lang/ispc-1.12.0/work/ispc-1.12.0
clangSemaPath
    linked by target "ispc" in directory /var/tmp/portage/dev-lang/ispc-1.12.0/work/ispc-1.12.0
clangSerializationPath
    linked by target "ispc" in directory /var/tmp/portage/dev-lang/ispc-1.12.0/work/ispc-1.12.0
```
I have the clang libraries installed.

I tried to fix this myself, but failed. However, I have a few comments:
- An ISPC versions seems to be restricted to an LLVM version (at least it needs a specific minimum version). If this is true, it should be forced in the ebuild (the ebuild then also must ensure, that cmake uses the correct version, especially if multiple LLVM versions are installed). Unfortunately, I don't know, how this can be achieved. I heard that Gentoo has some tooling for this already. For me, it always finds LLVM 10 (while I have also 8 and 9 installed).
- ISPC released a [new version](https://github.com/ispc/ispc/releases/tag/v1.13.0) two weeks ago, that is based on LLVM 10 as backend.
- I tried to package ISPC-1.13.0. One newly bug is, that ISPC [force](https://github.com/ispc/ispc/blob/master/CMakeLists.txt#L138) `CMAKE_BUILD_TYPE` to be `Release`, `Debug` or `RelWithDebInfo`, while Gentoo sets `Gentoo` as `CMAKE_BUILD_TYPE` by default. I could fix that by adopting the same lines as in [llvm-ocaml](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-ml/llvm-ocaml/llvm-ocaml-9.0.1.ebuild#n39).
- At least 1.13.0 searches in the build process for Python3. I think, this should be added as BDEPEND then.
- The ebuild for 1.13.0 then triggers exactly the same error as reported above.

**Comment by waebbl** [comment]
Hello @gerion0, I had the issue too when trying to prepare an ebuild for 1.12.0. The reason are the changes in clang library packaging (c.f. https://archives.gentoo.org/gentoo-dev/message/6d3cf88d858fcf3fbb11818ce5d6ea42). These changes need some more fixes in the build system.

**Comment by gerion0** [comment]
Hmm, then the quick fix (for 1.12) would be to force the Clang version to <=9.

**Comment by redchillipadi** [comment]
I have the same issue, and have found that the llvm eclass does not limit the version of llvm used in the build. I will look into this soon as I need ispc to compile for testing oidn with blender

**Comment by redchillipadi** [comment]
I have altered the ebuild to patch cmake/LLVMConfig.cmake so that it searches for the appropriate LLVM version. This fixes the issue for me

**Comment by redchillipadi** [comment]
I have no issues with 1.14.0 in the tree, closing this for now
