### ISSUE TITLE
Gentoo graphics project packages

### ISSUE THREAD

**Issue by waebbl** [redchillipadi/ebuild-overlay#15]
Hi Adrian,

maybe you have got notice of https://archives.gentoo.org/gentoo-dev/message/4085693739a978bffa168d14b6bcd6e5. The graphics project has been disbanded and there are a few packages, namely blender, ocio and oiio up for grab. Maybe you're interested in grabbing these for maintenance? If you like, I'd be happy to co-maintain them.

Cheers,
Bernd

**Comment by redchillipadi** [comment]
Hi Bernd,

Thanks, I am keen to ensure that all packages needed for blender are maintained and would be happy to co-maintain then with you. I was planning to ask about those exact three you mentioned.

Cheers,
Adrian

Update: I have posted on proxy-maint that we are both interested to co-maintain these packages.
