### ISSUE TITLE
media-gfx/openvdb-{5.2.0,7.0.0} fails to properly configure

### ISSUE THREAD

**Issue by waebbl** [redchillipadi/ebuild-overlay#3]
I haven't tried 6.2.1.
Both fail with a similar error on boost_python.

5.2.0:
```
CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:2020 (message):
  No header defined for python-3.6; skipping header check (note: header-only
  libraries have no designated component)
Call Stack (most recent call first):
  openvdb/python/CMakeLists.txt:6 (FIND_PACKAGE)


CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: python-3.6) (found version "1.71.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindBoost.cmake:2179 (find_package_handle_standard_args)
  openvdb/python/CMakeLists.txt:6 (FIND_PACKAGE)
```

7.0.0:
```
-- Found Python: /usr/bin/python3.8) (found suitable version "3.8.1", minimum required is "2.7")
CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:2020 (message):
  No header defined for python-38; skipping header check (note: header-only
  libraries have no designated component)
Call Stack (most recent call first):
  openvdb/python/CMakeLists.txt:153 (find_package)


CMake Error at openvdb/python/CMakeLists.txt:175 (message):
  Unable to find boost_python38, boost_python3 or boost_python.
```

Looks like the selection of boost and python packages could need some improvement. I'm having python 3.{6,7,8} installed, but so far only boost-1.71.0 which doesn't support python 3.8 (can't update at this time, due to some packages still need python 2.7 boost, which isn't available anymore in boost-1.72.0-r1. Additionally blender-2.81a doesn't support python-3.8, so this should IMO be excluded from the search.

**Comment by redchillipadi** [comment]
I am working on incorporating your fixes into openvdb. They do resolve the above issue, but when I enable the new numpy USE flag, I get a similar error.

```
-- Found Python: /usr/bin/python3.7) (found suitable version "3.7.7", minimum required is "2.7")
-- Found NumPy: /usr/lib/python3.7/site-packages/numpy/core/include (found suitable version "1.17.4", minimum required is "1.12.1")
-- Found boost_python37
CMake Error at openvdb/python/CMakeLists.txt:209 (message):
  Unable to find boost_numpy37, boost_numpy3 or boost_numpy.
```

Did you get numpy to work on your system? Perhaps I have not integrated your changes properly.

**Comment by waebbl** [comment]
Yes it's working on my system. I have numpy and boost[numpy] installed, as well as numpy-python2 (still needed by 2 packages).
The error above looks like you have boost installed without numpy USE flag. You might also try to update to numpy-1.18.

**Comment by redchillipadi** [comment]
Thanks, boost[numpy] was masked in package.use.stable.mask so it wasn't compiled in. Now openvdb compiles with numpy enabled
