### ISSUE TITLE
=media-gfx/blender-2.81a can't be build against openvdb::gentoo

### ISSUE THREAD

**Issue by waebbl** [redchillipadi/ebuild-overlay#4]
Because of issue #3 I was thinking to use ::gentoo provided openvdb ebuild to build blender. I know blender supports abi version 5 and AFAIR also 4.
The dependencies though couldn't be solved due to USE flag restrictions in the blender ebuild.
I was able to get the dependency tracking right, by using the patch:
```
diff --git a/media-gfx/blender/blender-2.81a.ebuild b/media-gfx/blender/blender-2.81a.ebuild
index 30cf0f9..c06b145 100644
--- a/media-gfx/blender/blender-2.81a.ebuild
+++ b/media-gfx/blender/blender-2.81a.ebuild
@@ -24,8 +24,7 @@ IUSE="+bullet +dds +elbeem +openexr +system-python +system-numpy \
 	alembic collada color-management cuda cycles debug doc \
 	draco embree ffmpeg fftw headless jack jemalloc jpeg2k libav llvm \
 	man ndof nls oidn openal opencl openimageio openmp opensubdiv \
-	openvdb openvdb_abi_4 openvdb_abi_5 openvdb_abi_6 openvdb_abi_7 \
-	osl sdl sndfile standalone test tiff valgrind"
+	openvdb osl sdl sndfile standalone test tiff valgrind"
 
 REQUIRED_USE="${PYTHON_REQUIRED_USE}
 	alembic? ( openexr )
@@ -34,11 +33,6 @@ REQUIRED_USE="${PYTHON_REQUIRED_USE}
 	draco? ( !system-python !system-numpy )
 	embree? ( cycles )
 	opencl? ( cycles )
-	openvdb? ( || ( openvdb_abi_4 openvdb_abi_5 openvdb_abi_6 openvdb_abi_7 ) )
-	openvdb_abi_4? ( openvdb )
-	openvdb_abi_5? ( openvdb )
-	openvdb_abi_6? ( openvdb )
-	openvdb_abi_7? ( openvdb )
 	osl? ( cycles llvm )
 	standalone? ( cycles )"
 
@@ -89,7 +83,7 @@ RDEPEND="${PYTHON_DEPS}
 	)
 	opensubdiv? ( >=media-libs/opensubdiv-3.4.0:=[cuda=,opencl=] )
 	openvdb? (
-		>=media-gfx/openvdb-5.2.0:=[-openvdb_abi_3,openvdb_abi_4=,openvdb_abi_5=]
+		>=media-gfx/openvdb-5.2.0:=[abi4-compat(+),-openvdb_abi_3(-),openvdb_abi_4(+),openvdb_abi_5(+)]
 		dev-cpp/tbb
 		dev-libs/c-blosc
 	)
@@ -154,18 +148,7 @@ src_configure() {
 	append-flags -funsigned-char
 	append-lfs-flags
 
-	openvdb_version=0
-	if use openvdb_abi_4; then
-		openvdb_version=4
-	elif use openvdb_abi_5; then
-		openvdb_version=5
-	elif use openvdb_abi_6; then
-		openvdb_version=6
-	elif use openvdb_abi_7; then
-		openvdb_version=7
-	fi
-	[ openvdb_version > 0 ] || die "Openvdb ABI version not specified"
-	append-cppflags -DOPENVDB_ABI_VERSION_NUMBER="${openvdb_version}"
+	append-cppflags -DOPENVDB_ABI_VERSION_NUMBER="5"
 
 	local mycmakeargs=(
 		-DPYTHON_VERSION="${EPYTHON/python/}"
```

IMO transporting the `openvdb_abi_{3,4,5,6,7}` USE flags from openvdb to blender isn't the best way to ensure proper ABI selection. In the first place, letting the user specify which ABI to use for openvdb, doesn't look sensible to me. Instead the consumer, i.e. blender should specify which ABI is needed. This is the way I choose for the patch above, omitting ABI 4, as this is marked deprecated in openvdb-7.0.0.
Another way could be to use the default ABI, i.e. use ABI 5 for openvdb-5.2.0, ABI 6 for openvdb-6.2.1 and ABI 7 for openvdb-7.0.0. Additional ABIs could be enable with USE flags on openvdb, but they don't need to be transported to consumers of openvdb in the first place.

What do you think?

**Comment by redchillipadi** [comment]
Thank you for your comment. I don't know the best answer to this problem. I do like the way both of your ideas simplify the ebuilds.

My problem is that the user may require a specific version of openvdb to be installed based on other packages that they use. If someone has bought a license for Houdini and installed it, they would need ABI 5 for Houdini 17, and ABI 6 for the current Houdini 18. If they didn't purchase the annnual upgrade plan, they may not be able to change Houdini versions freely. Only one ABI can be installed on a system. If the blender ebuild forces a specific ABI version, this would prevent some users from being able to install blender alongside Houdini, even though blender can compile with ABI 4-7.

There are three packages which need to know the ABI version - OpenVDB 7 now supports only ABI 5-7, blender can use ABI 4-7, and OpenImageIO 2 (once I get it updated) compiles with ABI 5-7

Ideally blender would be able to specify that it needs ABI >= 4, and OpenVDB and OpenImage could say they need ABI >=5. Then if someone made a Houdini ebuild using ABI 6 only, everything would be compile with ABI 6. I don't think it is possible to do this.

I see it more like python_single_target, which is specified by the user and controls which version of python each package is built against. Perhaps there is a need an openvdb.eclass, which creates appropriate dependency definitions for the ebuilds. I will look into this further and see if it can help to solve issue #3

**Comment by waebbl** [comment]
Thank you for your reply. I see your points and agree with the implied issues.

Currently we have only one revdep for openvdb, namely blender. But this will likely increase in the future. I was thinking on making a houdini apprentice ebuild for some time and your upcoming updated OIIO release, so this is something which should IMO be addressed.

I'm more optimistic that this could be solved with an eclass. Also, there could be a possibility for slotting, so more than one version can be installed at the same time, although this will require a deeper intrusion into the upstream build system, but I haven't looked into any of those possibilities yet.

Issue #3 is unrelated to the ABI problem, I think. I have solved that issue with some updates to your 7.0.0 ebuild in my overlay. You might want to check it out and incorporate the necessary changes into your ebuild. I can also clean it up of comments and open a PR if you like.

**Comment by redchillipadi** [comment]
I have got a working concept for the eclass, which is in the eclass branch and is heavily modelled on python-single-r1.eclass.

The user puts OPENVDB_ABI_VERSION in make.conf to specify the version for the system

Each package needs to set:
OPENVDB_COMPAT to the versions supported
inherit openvdb
IUSE="${OPENVDB_USE_FLAGS}"
REQUIRED_USE="openvdb? ( ${OPENVDB_REQUIRED_USE} )"
RDEPEND="openvdb? ( media-gfx/openvdb[${OPENVDB_SINGLE_USEDEP}] )"
and pass the version to the build system during configure eg
local mycmakeargs=( -DOPENVDB_ABI_VERSION_NUMBER="${OPENVDB_ABI_VERSION}" )

I haven't worked out how to create USE_EXPAND variables, but think that it might be possible to use them to remove the IUSE="${OPENVDB_USE_FLAGS}" requirement

It needs lots of testing to make sure it can cope with
Missing OPENVDB_ABI_VERSION specification
OPENVDB_ABI_VERSION incorrect (not in list, not possible to satisfy all packages, multiple values given)
OPENVDB_ABI_VERSION changes (to ensure all packages rebuild)

While updating USD I found that it doesn't directly depend on OpenVDB, only via OpenImageIO, so it does not need to use the eclass. The only classes that will need it will be blender, openimageio, openvdb and potentially Houdini.

**Comment by waebbl** [comment]
Good work so far :+1: 
When it comes to USE_EXPAND, they have to be used by more than just a single package, which is the case here, so it might get added. You have to go through the gentoo-dev mailinglist and ask for adding it. The same holds for the eclass, it needs to be discussed on the list before it can get added.

**Comment by redchillipadi** [comment]
Thanks, I am preparing to ask on the mailing list, I just want test the USE_EXPAND will work on my system first.

I now think that it should be called OPENVDB_ABI rather than OPENVDB_ABI_VERSION, as setting OPENVDB_ABI="5" will then expand to openvdb_abi_5 etc for IUSE. However as you know we need access to the variable's value in the ebuild for passing to cmake.

My current issue is that whenever I declare the OPENVDB_ABI USE_EXPAND variable in /usr/portage/profiles/base/make.defaults, the eclass gets an empty string for OPENVDB_ABI. If I don't declare it as USE_EXPAND, it gets the appropriate value that I set in make.conf. I wonder if it is being unset when it is expanded but haven't found the code where this occurs yet.

If this is the case then I will need to regenerate the version number from an if statement.
```
if use openvdb_abi_4; then
	openvdb_version=4
elif use openvdb_abi_5; then
	openvdb_version=5
elif use openvdb_abi_6; then
	openvdb_version=6
elif use openvdb_abi_7; then
	openvdb_version=7
fi
```
but I thought the whole point of the eclass was to avoid this. At least it hides it in one place. Actually this doesn't work as use() calls are not allowed in global scope

**Comment by waebbl** [comment]
Have you also created a proper description file in profiles/desc? AFAIK this is mandatory and probably needed for proper working of USE_EXPAND flags.

**Comment by redchillipadi** [comment]
Unfortunately I have done this already.

The changes outside of my repository are to:
Add OPENVDB_ABI to USE_EXPAND in /usr/portage/profiles/base/make.defaults
Create /usr/portage/profiles/desc/openvdb_abi.desc to describe the USE flags
Set OPENVDB_ABI="5" in /etc/portage/make.conf

**Comment by redchillipadi** [comment]
I think I have figured it out. The issue is that the USE_EXPAND flags are not available in the eclass from global scope, the only thing I have to set the global variables is OPENVDB_COMPAT. However OPENVDB_ABI is available directly in the ebuild during src_configure. A bit more bug testing and rewriting the documentation and I should have something ready for the mailing list

**Comment by redchillipadi** [comment]
I looked into Houdini apprentice, but it packages a binary library for a modified openvdb, so it will not need to link to openvdb.

But the eclass does help to ensure consistency between the abi used for openvdb, openimageio and blender, and the USE_EXPAND flag prevents a proliferation of openvdb_abi_X flags for each package.

**Comment by redchillipadi** [comment]
Now that openvdb 7.0 and blender 2.80+ are in the tree, this issue is resolved
