### ISSUE TITLE
media-gfx/blender: EAPI=7 bump

### ISSUE THREAD

**Issue by jonasstein** [redchillipadi/ebuild-overlay#7]
please bump to EAPI=7

**Comment by redchillipadi** [comment]
Fixed with commit 1d5983d616744d8c4748beae3522d4831bc43e16

Interestingly, the update to EAPI 7 seems to have altered cmake to build shared rather than static libraries. This produced a cyclic dependency between various shared portions of Cycles. The fix is to set BUILD_SHARED_LIBS=OFF

**Comment by waebbl** [comment]
Nice, thank you. I had this issue too, when I played around with updating to EAPI 7 some time ago, but couldn't resolve it.
