### ISSUE TITLE
Missing dependency to dev-cpp/tbb

### ISSUE THREAD

**Issue by gerion0** [redchillipadi/ebuild-overlay#9]
Apearently Blender depends on TBB (in the default configuration) and fails with a completely dubious error message, when TBB is not present:
```
...
-- Performing Test CXX_HAS_AVX2
-- Performing Test CXX_HAS_AVX2 - Success
-- Performing Test _has_cxxflag_float_conversion
-- Performing Test _has_cxxflag_float_conversion - Success
-- Performing Test _has_cxxflag_double_promotion
-- Performing Test _has_cxxflag_double_promotion - Success
-- Performing Test _has_no_error_unused_macros
-- Performing Test _has_no_error_unused_macros - Success
CMake Error at source/creator/CMakeLists.txt:50 (list):
  list sub-command INSERT requires at least three arguments.


CMake Error at source/creator/CMakeLists.txt:78 (blender_include_dirs):
  blender_include_dirs Function invoked with incorrect arguments for function
  named: blender_include_dirs
...
```

Following this error, it searches for TBB in the build files, given that the `WITH_TBB` option is set. From the main CMakeLists file, this is said for `WITH_TBB`:
```
option(WITH_TBB   "Enable features depending on TBB (OpenVDB, OpenImageDenoise, sculpt multithreading)" ON) 
```

Installing `dev-cpp/tbb` solves the configure error. So I think that the ebuild should either hard depend on tbb and setting the `WITH_TBB` option explicitly or toggle `WITH_TBB` dependend on a use flag and let depend openvdb etc. also on it.

This error happens in 2.82 and 2.82a for me.

**Comment by redchillipadi** [comment]
Thanks, I have added tbb as new USE flag. It is required for openvdb, oidn, elbeem (and usd once I get it working). If those flags are not used, then blender compiles for me with tbb disabled. I have enabled tbb by default as elbeem is in the default set.
